# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b5f0731afd72f50a28291643c4178a2df0d1821b50955fbc21800598ceca888152a3afa723b7896993f829043ff5617c2f28f8a7ebde38a5c7e65dc429aaea

test:
  secret_key_base: 53a16e8e8953a2051968fc8d0d645ff15920f8ce52f93eff684bbf12c907599baad4bcc2578c517753a3e330feca3f3f410a2a08e08f46a9e118e6e51aceb7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
